trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run Farmer'
  inputs:
    command: 'run'

- task: AzureResourceGroupDeployment@2
  displayName: 'Deploy ARM template'
  inputs:
    azureSubscription: '<enter subscription name here>'
    resourceGroupName: farmer-rg
    location: NorthEurope
    csmFile: output.json